# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
  schedule:
  - cron: '00 8,18 * * ?'
  - cron: '20,30,40, 8,9,10,11,12,13,14,18 * * ?'
  

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
       node-version: ${{ matrix.node-version }}
        
    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install
    - run: node robot.js
